image: archlinux
packages: 
  - nodejs
  - npm
  - docker
sources:
  - https://git.sr.ht/~erikcraddock/erikvancraddock.com
secrets:
  - 6b4c020e-b1c7-4e4f-9aea-1f2584149be1
tasks:
  - setup: |
      sudo systemctl enable --now docker
      npm install astro
  - build: |
      cd erikvancraddock.com
      npm install
      npm run build
  - deploy: |
      cd erikvancraddock.com
      export VERSION=$(node -e 'console.log(require("./package.json").version)')
      docker build -t evcraddock/erikvancraddock:$VERSION.$JOB_ID .
      cat ~/.docker-secret | docker login -u evcraddock --password-stdin 
      docker push evcraddock/erikvancraddock:$VERSION.$JOB_ID
      #      curl --insecure -X POST $(<~/.webhook-url)$VERSION.$JOB_ID

