name: Build and Deploy personal website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Astro.js project
        run: npm run build

      - name: Extract version from package.json
        id: set_image_tag
        run: |
          version=$(node -p -e "require('./package.json').version")
          patch_version=$(date +'%s')
          image_tag="${version}.${patch_version}"
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/erikvancraddock:${{ steps.set_image_tag.outputs.image_tag }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/erikvancraddock:${{ steps.set_image_tag.outputs.image_tag }}
