name: Build and Deploy personal website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from package.json
        id: set_image_tag
        run: |
          version=$(node -p -e "require('./package.json').version")
          patch_version=$(date +'%s')
          image_tag="${version}.${patch_version}"
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/erikvancraddock:${{ steps.set_image_tag.outputs.image_tag }}
            ${{ secrets.DOCKER_USERNAME }}/erikvancraddock:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/erikvancraddock:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/erikvancraddock:buildcache,mode=max
